name: 'GitHub LLM Actions System'
description: 'Process actions from GitHub issues using a reducer system'
inputs:
  github-token:
    description: 'GitHub token with write permissions to the repository'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-circle'
  color: 'blue'