name: LLM Actions System

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  reaction:
    types: [created]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run Action AI
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          llm-api-key: ${{ secrets.LLM_API_KEY }}
          llm-model: ${{ vars.LLM_MODEL || 'claude-3.7-sonnet-20250219' }}
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ vars.LLM_MODEL || 'claude-3.7-sonnet-20250219' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}