name: Issue Action

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  process-issue:
    runs-on: ubuntu-latest
    
    # Define environment variables at the job level
    env:
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_MODEL: ${{ vars.LLM_MODEL || 'claude-3.7-sonnet-20250219' }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Process Issue
        run: node dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ vars.LLM_MODEL || 'claude-3.7-sonnet-20250219' }}