name: Issue Response

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # No need for build steps since we're using pre-built code
      
      - name: Respond to issue
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}